export const AUTHENTICATED = 'AUTHENTICATED';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';

export const LOADING_USERS = 'LOADING_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const LOADING_BOTTLES = 'LOADING_BOTTLES';
export const GET_BOTTLES = 'GET_BOTTLES';
