export const AUTHENTICATED = 'AUTHENTICATED';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';

export const LOADING_USERS = 'LOADING_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const LOADING_BOTTLES = 'LOADING_BOTTLES';
export const GET_BOTTLES_SUCCESS = 'GET_BOTTLES_SUCCESS';
export const GET_BOTTLES_FAILURE = 'GET_BOTTLES_FAILURE';

export const LOADING_ORDERS = 'LOADING_ORDERS';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';

export const POSTING_ORDER = 'POSTING_ORDER';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAILURE = 'POST_ORDER_FAILURE';
