export const AUTHENTICATED = 'AUTHENTICATED';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';

export const LOADING_USERS = 'LOADING_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const LOADING_BOTTLES = 'LOADING_BOTTLES';
export const GET_BOTTLES_SUCCESS = 'GET_BOTTLES_SUCCESS';
export const GET_BOTTLES_FAILURE = 'GET_BOTTLES_FAILURE';

export const POSTING_BOTTLE = 'POSTING_BOTTLE';
export const POST_BOTTLE_SUCCESS = 'POST_BOTTLE_SUCCESS';
export const POST_BOTTLE_FAILURE = 'POST_BOTTLE_FAILURE';

export const PATCHING_BOTTLE = 'PATCHING_BOTTLE';
export const PATCH_BOTTLE_SUCCESS = 'PATCH_BOTTLE_SUCCESS';
export const PATCH_BOTTLE_FAILURE = 'PATCH_BOTTLE_FAILURE';

export const DELETING_BOTTLE = 'DELETING_BOTTLE';
export const DELETE_BOTTLE_SUCCESS = 'DELETE_BOTTLE_SUCCESS';
export const DELETE_BOTTLE_FAILURE = 'DELETE_BOTTLE_FAILURE';

export const LOADING_ORDERS = 'LOADING_ORDERS';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';

export const POSTING_ORDER = 'POSTING_ORDER';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAILURE = 'POST_ORDER_FAILURE';

export const LOADING_COUNTRIES = 'LOADING_COUNTRIES';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_FAILURE = 'GET_COUNTRIES_FAILURE';

export const LOADING_PRODUCERS = 'LOADING_PRODUCERS';
export const GET_PRODUCERS_SUCCESS = 'GET_PRODUCERS_SUCCESS';
export const GET_PRODUCERS_FAILURE = 'GET_PRODUCERS_FAILURE';

export const LOADING_VARIETALS = 'LOADING_VARIETALS';
export const GET_VARIETALS_SUCCESS = 'GET_VARIETALS_SUCCESS';
export const GET_VARIETALS_FAILURE = 'GET_VARIETALS_FAILURE';

export const LOADING_BINS = 'LOADING_BINS';
export const GET_BINS_SUCCESS = 'GET_BINS_SUCCESS';
export const GET_BINS_FAILURE = 'GET_BINS_FAILURE';
